### ISSUE TITLE
beginner needs help

### ISSUE THREAD

**Issue by praja83** [XRPL-Labs/xumm-api#1]
Hi,
I would like to install and start xumm-api, but I am beginner, could somebody help me?
I finally run npm install as bitnami user without errors, what is next?
I use aws lightsale - ubuntu, bitnami. I would like to implement XRP payments to my auction server (PHP Pro Bid).
Thanks,
Jiri

bitnami@ip-172-26-14-187:~$ npm config ls -q
; cli configs
loglevel = "warn"
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.13.6 node/v13.7.0 linux x64"

; userconfig /home/bitnami/.npmrc
prefix = "/home/bitnami"

; node bin location = /usr/bin/node
; cwd = /home/bitnami
; HOME = /home/bitnami
; "npm config ls -l" to show all defaults.

**Comment by WietseWind** [comment]
Hi,

Are you sure you want to run the XUMM API service, or do you want to *use* the XUMM API?

To use the XUMM API (register an app, call the API) please visit http://xumm.readme.io for the docs, and https://apps.xumm.dev for the developer console.

If you wish to *run* the API, clone the repository, run `npm install`, make sure to run a MySQL/MariaDB, populate the schema, a Redis instance and make sure you got the right data in the config.

I will add the schema, sample config and docker-compose to the repository soon.

However, based on what you wrote (implement XRP payments) I don't think you'll have to run the API, you can just consume the XUMM API that's already available on the links I just posted.

**Comment by praja83** [comment]
> Hi,
> 
> Are you sure you want to run the XUMM API service, or do you want to _use_ the XUMM API?
> 
> To use the XUMM API (register an app, call the API) please visit http://xumm.readme.io for the docs, and https://apps.xumm.dev for the developer console.
> 
> If you wish to _run_ the API, clone the repository, run `npm install`, make sure to run a MySQL/MariaDB, populate the schema, a Redis instance and make sure you got the right data in the config.
> 
> I will add the schema, sample config and docker-compose to the repository soon.
> 
> However, based on what you wrote (implement XRP payments) I don't think you'll have to run the API, you can just consume the XUMM API that's already available on the links I just posted.
